### ISSUE TITLE
How to compatible with BLE 4.0

### ISSUE THREAD

**Issue by WANG-lp** [tmk/HHKB_controller#19]
Hi, this is an awesome project.

But I have one question. The new Bluetooth tech will be more energy efficient than former version, does this controller support the Bluetooth 4.0?

**Comment by tmk** [comment]
Hi,
No, it supports only classic.

**Comment by willin** [comment]
is it bt dual-mode?

**Comment by tmk** [comment]
what is dual-mode? do you have some refrence for that?

**Comment by willin** [comment]
both usb and bluetooth can work

**Comment by tmk** [comment]
hmm, OK, I think "dual-mode" menas to support both BLE and Classic.
https://stackoverflow.com/questions/38066185/where-is-the-bluetooth-dual-mode-definition

RN42 module this controler uses is not "dual-mode".
